apiVersion: v1
kind: Service
metadata:
  name: citrix-sf-svc
  labels: 
    app: citrix-sf-svc
spec:
  type: NodePort
  selector:
    app: citrix-sf  
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30001
